---
root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - jest
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:jest/recommended
  - prettier
rules:
  react/jsx-uses-react: off
  react/react-in-jsx-scope: off
ignorePatterns:
  - dist/*
  - graphql.schema.json
  - src/generated/*
